spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/example
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create